language: R
dist: trusty  # ubuntu 14.04 has additional libraries available
sudo: false
cache: packages
warnings_are_errors: false

# update pre-installed packages to latest versions
before_install:
  Rscript -e 'update.packages(ask = FALSE)'

# last stable version of devtools does not support private depositories
r_github_packages: hadley/devtools#1263

notifications:
  slack:
    rooms:
      - numbers:FTgSTNHC2rpanhJMGTKMwZXM#github-notifications
    template:
      - "Build <%{build_url}|#%{build_number}> %{result} in %{repository_name}@%{branch} by %{author}: <%{compare_url}|%{commit_message}>"
    on_success: change
    on_failure: always

after_success: >-
  if [ $TRAVIS_EVENT_TYPE == "push" ] ; then
    curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token $ACCESS_TOKEN" -d '{"request":{"message":"Build triggered by flipMultivariates", "branch":"master"}}' "https://api.travis-ci.org/repo/NumbersInternational%2FflipCluster/requests";
  fi
